#!/bin/sh
set -e
cd /rails
bundle install --without development test --path vendor/bundle
bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rake db:seed
bundle exec rake assets:precompile
